-- Первод ZamestoTV
local L = LibStub("AceLocale-3.0"):NewLocale("SteaSummon", "ruRU", true)

L["Language"] = "Язык"

--- main.lua
L["Summon Next"] = "Призвать следующего"
L["Set Destination"] = "Установить место назначения"

--- chat.lua
L["list"] = "список"
L["%name waiting: %number seconds"] = "%name ожидает: %number секунд"
L["Summon waiting list"] = "Очередь на призыв"
L["%count waiting"] = "Ожидают: %count"
L["debug"] = "отладка"
L["on"] = "вкл"
L["off"] = "выкл"
L["add"] = "добавить"

--- raid.lua
L["Warlocks"] = "Чернокнижники"
L["Clickers"] = "Кликающие"

--- settings.lua
L["Summoning %p"] = "Призываем %p"
L["Summoning you to %l in %z"] = "Призываем вас в %l, %z"
L["Summoning %p, please click the portal"] = "Призываем %p, пожалуйста, кликните портал"
L["raidinfo"] = "Призыв доступен. Напишите %t для запроса призыва, -%t для отмены, %t для сброса статуса при ошибке"
L["clickersnag"] = "Нужно больше людей для клика портала в %l, %z"
L["clicknag"] = "Кликните портал призыва!"
L["You are in the summon queue. Whisper me an alt name if you don't want to wait online."] = "Вы в очереди на призыв. Шепните мне имя вашего альт-персонажа, если не хотите ждать в сети."
L["You are near the top of the summon queue. Get online now."] = "Вы почти в начале очереди на призыв. Войдите в игру сейчас."

--- summon.lua
L["Warlock"] = "Чернокнижник"
L["W"] = "Ч"
L["requested"] = "запрошено"
L["Buffed"] = "С баффами"
L["B"] = "Б"
L["Prioritized"] = "Приоритет"
L["P"] = "П"
L["Last"] = "Последний"
L["L"] = "П"
L["Normal"] = "Обычный"
L["N"] = "О"
L["dead"] = "мертв"
L["offline"] = "не в сети"
L["pending"] = "в процессе"
L["Imagine not having enough mana."] = "Представьте, что у вас не хватает маны. А теперь представьте, что вы шепчете это себе, когда у вас действительно не хватает маны."
L["Reason for list placement"] = "Причина позиции в списке"
L["[W]arlock, [B]uffs, [P]riority, [N]ormal, [L]ast"] = "[Ч]ернокнижник, [Б]аффы, [П]риоритет, [О]бычный, [П]оследний"
L["summoned"] = "призван"
L["Location: %subzone, %zone"] = "Местоположение: %subzone, %zone"
L["Destination: %subzone, %zone"] = "Назначение: %subzone, %zone"
L["Next"] = "Следующий"
L["Alt:"] = "Альт:"
L["Request"] = "Запрос"
L["Reset"] = "Сброс"
L["accepted"] = "принято"
L["declined"] = "отклонено"

--- optionsgui.lua
L["One button summoning, shared summoning list...    (Options for: %name)"] = "Призыв одной кнопкой, общий список призыва... (Настройки для: %name)"

-- window
L["Help"] = "Помощь"
L["plushelp"] = "Используйте эту кнопку для открытия дерева настроек под основным интерфейсом SteaSummon. Здесь много опций. Уделите время изучению параметров в каждом разделе и настройте их по своему вкусу. Все настройки сохраняются для каждого персонажа отдельно.\n\n"
L["summonhelp"] = "Кнопка призыва вызывает следующего игрока со статусом 'запрошено'. При призыве статус меняется на 'в процессе', и все игроки с SteaSummon видят это изменение. Другие чернокнижники с SteaSummon автоматически призовут следующего игрока после того, кого вы призываете. Эта кнопка отображается только для чернокнижников 20+ уровня, когда в списке есть ожидающие призыва.\n\nВы можете назначить горячую клавишу для этой кнопки в основном меню назначения клавиш, в категории Модификаций.\n\n"
L["desthelp"] = "Место назначения для призыва устанавливается при начале призыва. Оно также устанавливается при нажатии кнопки информации о рейде и при явном указании в контекстном меню. Все члены рейда с SteaSummon видят место назначения.\n\nКогда место назначения установлено, только чернокнижники в этом месте могут управлять списком призыва, и только игроки в месте назначения будут видеть рядом находящихся людей из списка призыва. Игроки всегда могут управлять своей собственной записью в списке призыва.\n\nКроме ограничений управления списком, при установленном месте назначения количество чернокнижников и количество людей, доступных для клика портала, отображается для всех с SteaSummon.\n\n"
L["raidinfohelp"] = "Кнопка информации о рейде управляет периодическими сообщениями в рейд и отображается только для чернокнижников 20+ уровня.\n\nПервое сообщение просит больше людей прибыть к месту назначения для начала призыва. Оно появляется, когда там менее 3 человек или нет чернокнижника.\n\nВторое сообщение информирует рейд о доступности призыва и дает краткие инструкции по запросу, отмене и обновлению призыва. Это сообщение появляется, когда в месте назначения хотя бы 3 человека, включая чернокнижника 20+ уровня.\n\nВы можете назначить горячую клавишу для этой кнопки в основном меню назначения клавиш, в категории Модификаций.\n\n"

-- display
L["Display"] = "Отображение"
L["General"] = "Общие"
L["Window Options"] = "Настройки окна"
L["Change the scale of the interface. Set the window to always show before adjusting scale in order to see the results."] = "Изменяет масштаб интерфейса. Установите постоянное отображение окна перед изменением масштаба, чтобы видеть результат."
L["Show Summon Window"] = "Показывать окно призыва"
L["Always"] = "Всегда"
L["Only when summons are active"] = "Только при активном призыве"
L["Only when I am in the active summon list"] = "Только когда я в списке призыва"
L["Never"] = "Никогда"
L["wnddesc"] = "Когда отображать интерфейс: всегда, при наличии ожидающих призыва, когда вы в списке призыва или никогда"
L["savedesc"] = "Если вы в группе при повторном входе в игру в течение этого времени, ваш список призыва сохраняется. Это сохраняет список, если все пользователи модификации вышли из игры."
L["Summon list save time (in minutes)"] = "Время сохранения списка призыва (в минутах)"
L["How long to preserve the summon list between logins"] = "Как долго сохранять список призыва между входами в игру"
L["Summon window scale"] = "Масштаб окна призыва"
L["wndscale"] = "Изменяет масштаб окна. Лучше установить 'Показывать всегда' для визуализации изменений."
L["Summon list scale"] = "Масштаб списка призыва"
L["sumscale"] = "Изменяет масштаб содержимого окна. Лучше установить 'Показывать всегда' для визуализации изменений."
L["Show minimap button"] = "Показывать кнопку у миникарты"
L["Toggle whether to show the minimap button"] = "Включить/отключить отображение кнопки у миникарты"

-- messages
L["Messages"] = "Сообщения"
L["Message Options"] = "Настройки сообщений"
L["msgopdesc"] = "Эти настройки могут содержать переменные с префиксом %, куда будет подставляться динамический текст. Пустые строки отключают функцию.\n\nДоступные переменные:\n\n%p : имя игрока\n%l : место призыва\n%z : зона призыва\n%t : первая фраза-триггер"
L["Summon raid notification text"] = "Текст уведомления о призыве в рейд"
L["a sentence that posts to raid when someone is summoned"] = "сообщение, отправляемое в рейд при призыве игрока"
L["Summon whisper notification text"] = "Текст уведомления шепотом при призыве"
L["a sentence that is whispered to the person being summoned"] = "сообщение, отправляемое шепотом призываемому игроку"
L["Summon portal click request in say"] = "Запрос клика портала в /сказать"
L["a sentence that posts to say to request others click on the portal"] = "сообщение, отправляемое в /сказать с просьбой кликнуть портал"
L["Raid summon instructions"] = "Инструкции по призыву в рейд"
L["a sentence that that posts to raid periodically"] = "сообщение, периодически отправляемое в рейд"
L["Raid request for clickers"] = "Запрос кликающих в рейд"
L["a sentence that that posts to raid periodically when there not enough clickers to summon"] = "сообщение, периодически отправляемое в рейд при нехватке кликающих портал"
L["Summoning portal click nag"] = "Напоминание о клике портала"
L["a sentence that posts to say when you click the Next button while casting"] = "сообщение в /сказать при нажатии кнопки 'Следующий' во время каста"
L["Raid summon instructions period (minutes)"] = "Период инструкций по призыву (минуты)"
L["How long to wait between sending to chat"] = "Как долго ждать между отправками в чат"
L["Raid clicker request period (minutes)"] = "Период запроса кликающих (минуты)"
L["Say clicker request period (seconds)"] = "Период запроса кликающих в /сказать (секунды)"

-- triggers
L["Trigger Phrases"] = "Фразы-триггеры"
L["Triggers"] = "Триггеры"
L["trigphrasedesc"] = "Фразы-триггеры - это фразы, которые игроки могут написать в чат рейда или группы, чтобы добавиться в список призыва. Игроки также могут написать '-' (минус) перед фразой-триггером, чтобы удалиться из списка."
L["Trigger phrases for summon. One per line."] = "Фразы-триггеры для призыва. По одной на строку."
L["chat lines that will add a summon request for the raider"] = "строки чата, которые добавят запрос на призыв"

-- priorities
L["Priorities"] = "Приоритеты"
L["Priority Options"] = "Настройки приоритетов"
L["Maximum warlocks first"] = "Максимум чернокнижников первыми"
L["Maximum summoners to be prioritized"] = "Максимальное количество призываемых с приоритетом"
L["These options determine where in the summon list players are inserted when they ask for a summon."] = "Эти настройки определяют позицию игроков в списке призыва при запросе."
L["Warlocks first"] = "Чернокнижники первыми"
L["Put unbuffed summoners at the top of the list when they request a summon"] = "Помещать непризванных чернокнижников в начало списка при запросе"
L["Prioritize buffed players"] = "Приоритет игроков с баффами"
L["Put players with world buffs ahead of named priority players"] = "Помещать игроков с мировыми баффами перед именными приоритетами"
L["Players to summon first, if by first, you mean behind warlocks and buffed players. One player per line."] = "Игроки для приоритетного призыва (после чернокнижников и игроков с баффами). По одному на строку."
L["These players will move to the front of the summon list when they request a summon"] = "Эти игроки будут перемещены в начало списка при запросе"
L["Players to summon last. Some people should just be nicer. One player per line."] = "Игроки для призыва последними. Некоторым стоит быть повежливее. По одному на строку."
L["These players will move to the back of the summon list and stay there"] = "Эти игроки будут перемещены в конец списка и останутся там"
L["Advanced"] = "Дополнительно"
L["Advanced Options"] = "Дополнительные настройки"
L["These are options that, should you change them, will blow up your computer."] = "Это настройки, которые при изменении могут взорвать ваш компьютер."
L["Debug"] = "Отладка"
L["Turn on debugging statements"] = "Включить отладочные сообщения"
L["Enable Experimental Features"] = "Включить экспериментальные функции"
L["This could be anything. It will probably be horribly broken, or worse, not do very much."] = "Это может быть что угодно. Вероятно, будет ужасно сломано или, что хуже, делать не очень много."
L["Reset to Defaults"] = "Сбросить настройки"
L["Reset all options to the default values"] = "Сбросить все настройки к значениям по умолчанию"
L["Use AddOn Broadcast Communications"] = "Использовать трансляцию данных аддона"
L["broadcastdesc"] = "Получать и отправлять обновления статуса призыва. Уведомляет об изменениях статуса и помогает сохранять список призыва между входами в игру. Делает кнопку 'Следующий' более эффективной при нескольких чернокнижниках. Пожалуйста, не отключайте."
L["Version Details"] = "Информация о версии"
L["SteaSummon version %s\n\nWoW client\nversion: %v\nbuild: %b\ndate: %d\ntocversion: %t"] = "SteaSummon версия %s\n\nКлиент WoW\nверсия: %v\nсборка: %b\nдата: %d\nверсия TOC: %t"

-- alts
L["Alt Support"] = "Поддержка альтов"
L["Alt Character Options"] = "Настройки альт-персонажей"
L["altdesc"] = "Эти настройки позволяют игрокам находиться на других персонажах во время ожидания призыва."
L["Enable only when player buffed"] = "Только для игроков с баффами"
L["altbuffeddesc"] = "Поддержка альтов активирует инструкции только для игроков с баффами (все игроки могут использовать поддержку альтов)"
L["Enable only when the queue spot reaches"] = "Только при достижении позиции в очереди"
L["qspotdesc"] = "Поддержка альтов активирует инструкции только когда игрок достигает или проходит эту позицию в очереди"
L["Whisper alts when they reach this queue spot"] = "Шептать альтам при достижении этой позиции"
L["Automatically register your characters for alt support"] = "Автоматически регистрировать ваших персонажей для поддержки альтов"
L["These are the characters you might be on when your summon is ready"] = "Это персонажи, на которых вы можете быть, когда призыв готов"
L["qspotreadydesc"] = "Поддержка альтов активирует уведомление только при достижении этой позиции в очереди"
L["When out of online players to summon, whisper this many extra alts"] = "Когда нет онлайн-игроков для призыва, шептать этому количеству альтов"
L["qspotboostreadydesc"] = "Поднимать игроков с их альтов для продолжения призыва"
L["Whisper instructional text"] = "Текст инструкции шепотом"
L["a sentence that is whispered to instruct the player how to add an alt for their summon"] = "сообщение с инструкцией шепотом, как добавить альт для призыва"
L["Whisper summon ready text"] = "Текст готовности призыва шепотом"
L["a sentence that is whispered to tell an alt their summon is ready"] = "сообщение шепотом альту о готовности призыва"

-- raid
L["Raid Management"] = "Управление рейдом"
L["Raid Management Options"] = "Настройки управления рейдом"
L["These options perform raid management actions to form your raid when you are raid leader."] = "Эти настройки выполняют действия по управлению рейдом, когда вы лидер."
L["Warlocks get assist"] = "Чернокнижники получают ассист"
L["Give assist status to unbuffed summoners"] = "Давать статус ассиста непризванным чернокнижникам"
L["Final raid leadership are named players"] = "Окончательное руководство рейдом - именные игроки"
L["When relinquishing leadership, ensure only the named players keep their roles"] = "При передаче лидерства оставлять роли только именным игрокам"
L["Delay leadership transfer"] = "Задержать передачу лидерства"
L["Only transfer leadership once the destination is unset and summons are over"] = "Передавать лидерство только после сброса места назначения и завершения призыва"
L["Players to give assist"] = "Игроки для получения ассиста"
L["These players will be given raid assist when they join the raid"] = "Эти игроки получат ассиста при присоединении к рейду"
L["Players to promote to leader"] = "Игроки для повышения до лидера"
L["leaderdesc"] = "Эти игроки получат ассиста, а затем (в порядке предпочтения) будут повышены до лидера при передаче лидерства"
L["Players to set as master looter"] = "Игроки для назначения ответственным за добычу"
L["mldesc"] = "Эти игроки получат ассиста, а затем (в порядке предпочтения) будут назначены ответственными за добычу при передаче лидерства"
L["Auto invite players who whisper these trigger words"] = "Автоприглашение игроков по триггер-словам"
L["These trigger words will trigger an invitation to the raid"] = "Эти слова-триггеры вызовут приглашение в рейд"
L["Enable auto invite"] = "Включить автоприглашение"
L["Allow people to request invites to the raid via whisper"] = "Разрешить запрос приглашений в рейд шепотом"
L["Only Guild"] = "Только гильдия"
L["Only Guild and Friends"] = "Только гильдия и друзья"
L["Anyone"] = "Любой"
L["Off"] = "Выкл"
L["Enable accept invites"] = "Принимать приглашения"
L["Accept group invites to the raid"] = "Принимать приглашения в группу/рейд"
L["Auto convert to raid"] = "Автопреобразование в рейд"
L["When you form a party, convert it to a raid"] = "При создании группы автоматически преобразовывать в рейд"
L["Automatic Invite Options"] = "Настройки автоприглашения"
L["These options determine how automatic invite and accept works"] = "Эти настройки определяют работу автоприглашения"

--- gossip.lua
L["There is a newer version available."] = "Доступна новая версия."
L["version"] = "Сетевое взаимодействие отключено. Ваша версия SteaSummon использует устаревший сетевой протокол. Вам следует обновиться и перезапустить клиент."

-- minimap.lua
L["SteaSummon Options"] = "Настройки SteaSummon"
L["Show/Hide Minimap Button"] = "Показать/Скрыть кнопку у миникарты"
L["Configuration"] = "Конфигурация"
L["Show/Hide Summon Window"] = "Показать/Скрыть окно призыва"
L["Key Bindings"] = "Назначение клавиш"
L["SteaSummon"] = "SteaSummon"
L["Options"] = "Настройки"
L["Toggle Raid Information"] = "Информация о рейде"
L["Set/Unset Destination"] = "Установить/Сбросить место назначения"
L["Request Summon"] = "Запросить призыв"
L["Reset Summon"] = "Сбросить призыв"
L["Cancel Summon"] = "Отменить призыв"
L["Relinquish Raid Lead"] = "Передать лидерство"
L["Clear Summon List"] = "Очистить список призыва"
L["clearlistdesc"] = "Это действие очистит список для всех в рейде. Вы можете просто скрыть окно. Вы уверены, что хотите продолжить?"
L["Manage List"] = "Управление списком"
L["Request/Reset Summon"] = "Запрос/Сброс призыва"